workflows:
  ios_dev:
    name: iOS Dev IPA
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: iOS build no codesign
        script: flutter build ios --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
