workflows:
  ios_unsigned:
    name: iOS unsigned build
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_NAME: "Runner"
    scripts:
      - name: "Ensure flutter packages (important: generates generated.xcconfig)"
        script: |
          flutter pub get
      - name: "Install pods"
        script: |
          cd ios
          pod install
          cd ..
      - name: "Build unsigned .ipa"
        script: |
          set -e
          flutter build ios --no-codesign
          mkdir -p build/ios/ipa
          cd build/ios/ipa
          cp -r ../iphoneos/Payload .
          zip -r ${APP_NAME}.ipa Payload
    artifacts:
      - build/ios/ipa/*.ipa
