workflows:
  ios_unsigned:
    name: iOS unsigned build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: "Clean project"
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock pubspec.lock
      - name: "Get Flutter packages (creates Generated.xcconfig)"
        script: |
          flutter pub get
          ls ios/Flutter || echo "Flutter folder will be generated on build"
      - name: "Run pod install (after flutter pub get)"
        script: |
          cd ios
          pod repo update
          pod install
          cd ..
      - name: "Build unsigned iOS .ipa (no codesign)"
        script: |
          # Сборка для симулятора (не требует подписи)
          flutter build ios --simulator --release

          # Создаём .ipa вручную
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/iphonesimulator/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r SmartAlarm.ipa Payload

    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your@email.com
