workflows:
  smart_alarm_ios:
    name: Smart Alarm iOS Dev Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS IPA (dev, no codesign)
        script: flutter build ios --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
