workflows:
  ios_unsigned:
    name: iOS unsigned build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: "Clean project"
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock pubspec.lock
      - name: "Get Flutter packages (creates Generated.xcconfig)"
        script: |
          flutter pub get
          ls ios/Flutter || echo "Flutter folder will be generated on build"
      - name: "Run pod install (after flutter pub get)"
        script: |
          cd ios
          pod repo update
          pod install
          cd ..
      - name: "Build unsigned iOS .ipa (no codesign)"
        script: |
          flutter build ios --release --no-codesign
          mkdir -p build/ios/ipa
          cd build/ios/ipa
          cp -r ../iphoneos/Payload .
          zip -r SmartAlarm.ipa Payload
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your@email.com
