workflows:
  ios_unsigned_simulator:
    name: Build unsigned iOS .ipa for simulator (no codesign)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Prepare Flutter and CocoaPods
        script: |
          flutter clean
          flutter pub get
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..
      - name: Build iOS app for simulator
        script: |
          flutter build ios --simulator
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/iphonesimulator/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r Runner.ipa Payload
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - misha2008200@gmail.com
