platform :ios, '14.0'

# Подключение Flutter
flutter_root = File.expand_path(File.join('..', '..'))
load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
